Making my Changes
hspahic-cs/WhisperRealtimeTranslation pull request #18
Opened 2023-04-18 20:15 UTC by BriannaPGarland

Adding the timer as well as adding some UI fixes for the frontend and adding the text to speech functionality

2023-04-18 22:45 UTC, uityh requested changes
I get an error when trying to run it. I think the react speech kit wasn't added to the package json.

2023-04-19 02:35 UTC, DanielleDauphinais commented
I get this error "Module not found: Error: Can't resolve 'react-speech-kit' in '/Users/danielle/Downloads/WhisperRealtimeTranslation-BrisAdditions/universal-translator/src/Components'"
Then when I tried to just install it this is the error that I get
<img width="586" alt="Screenshot 2023-04-18 at 10 29 42 PM" src="https://user-images.githubusercontent.com/72697849/232951125-fed1f2eb-73bd-420d-a5ae-6c4580833614.png">

2023-04-25 16:06 UTC, hspahic-cs approved these changes

2023-04-25 16:18 UTC, uityh approved these changes

2023-04-25 16:18 UTC, merged